/*Queries ON SEPCIAL OPERATORS*/
/*1)LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL */
SELECT * FROM EMP
WHERE COMM IS NULL;

/*2)LIST ALL THE EMPLOYEES WHO DON’T HAVE A
REPORTING MANAGER*/
SELECT * FROM EMP
WHERE JOB NOT IN('MANAGER')
AND JOB IS NOT NULL;

/*3)LIST ALL THE SALESMEN IN DEPT 30*/
SELECT * FROM EMP 
WHERE JOB ='SALESMAN'
AND DEPTNO=30;

/*4)LIST ALL THE SALESMEN IN DEPT NUMBER 
30 AND HAVING SALARY GREATER THAN 1500 */
SELECT * FROM EMP 
WHERE JOB ='SALESMAN' 
AND DEPTNO=30
AND SAL>1500 ;

/*5)LIST ALL THE EMPLOYEES WHOSE NAME STARTS
WITH ‘S’ OR ‘A’*/
SELECT * FROM EMP 
WHERE ENAME LIKE 'S%' 
OR ENAME LIKE 'A%';

/*6)LIST ALL THE EMPLOYEES EXCEPT THOSE 
WHO ARE WORKING IN DEPT 10 & 20.*/
SELECT * FROM EMP
WHERE DEPTNO NOT IN(10,20);

/*7)LIST THE EMPLOYEES WHOSE 
NAME DOES NOT START WITH ‘S’ */
SELECT * FROM EMP 
WHERE ENAME NOT LIKE 'S%';

/*8)LIST ALL THE EMPLOYEES WHO ARE 
HAVING REPORTING MANAGERS IN DEPT 10 */
SELECT * 
FROM EMP 
WHERE MGR IS NOT NULL
AND DEPTNO = 10;

/*9)LIST ALL THE EMPLOYEES WHOSE COMMISSION 
IS NULL AND WORKING AS CLERK */
SELECT * FROM emp
WHERE COMM IS NULL
AND JOB='CLERK';

/*10)LIST ALL THE EMPLOYEES WHO DON’T HAVE A
REPORTING MANAGER IN DEPTNO 10 OR 30 */
SELECT * 
FROM emp
WHERE MGR IS NULL
AND DEPTNO IN (10, 30);

/*11)LIST ALL THE SALESMEN IN DEPT
 30 WITH SAL MORE THAN 2450*/
 SELECT * FROM EMP 
 WHERE JOB='SALESMAN' AND DEPTNO=30
 AND SAL>2450;

/*12)LIST ALL THE ANALYST IN DEPT NUMBER 
20 AND HAVING SALARY GREATER THAN 2500 */
SELECT * FROM EMP 
WHERE JOB='ANALYST'
AND DEPTNO=20
AND SAL>2500;

/*13)LIST ALL THE EMPLOYEES WHOSE NAME STARTS
WITH ‘M’ OR ‘J’ */
SELECT * FROM EMP 
WHERE ENAME LIKE 'M%'
 OR ENAME LIKE 'J%';
 
 /*14)LIST ALL THE EMPLOYEES WITH ANNUAL SALARY 
 EXCEPT THOSE WHO ARE WORKING IN DEPT 30 */
 SELECT * ,SAL*12 AS 'ANNUAL SALARY'
 FROM emp
 WHERE DEPTNO!= 30;
 
 /*15)LIST THE EMPLOYEES WHOSE NAME 
 DOES NOT ENDWITH ‘ES’ AND ‘R’*/
 SELECT * FROM EMP 
 WHERE ENAME NOT LIKE '%ES' 
 AND ENAME NOT LIKE '%R';
 
 /*16)LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING 
 MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY */
SELECT *, SAL+SAL*10/100 AS "10%HIKE_SALARY"
FROM EMP 
WHERE MGR IS NOT NULL
AND DEPTNO=10;

/*17)DISPLAY ALL THE EMPLOYEE WHO ARE ‘SALESMAN’S HAVING 
‘E’ AS THE LAST BUT ONE CHARACTER IN ENAME.*/
SELECT * FROM EMP 
WHERE JOB = 'SALESMAN' 
AND ENAME LIKE '%E_';

/*18)DISPLAY ALL THE EMPLOYEE 
WHO ARE JOINED AFTER YEAR 81.*/
SELECT * FROM EMP 
WHERE HIREDATE > '1981-12-31';

/*19)DISPLAY ALL THE EMPLOYEE WHO 
ARE JOINED  DURING 1982. */
SELECT * FROM EMP 
WHERE HIREDATE BETWEEN '1982-01-01' AND '1982-12-31';

/*20)LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND 
CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000.*/
SELECT * FROM EMP 
WHERE JOB NOT IN('MANAGER','CLERK')
AND DEPTNO IN(10,20)
AND SAL BETWEEN 1000 AND  3000;




